### ISSUE TITLE
Exception in EclipseProjectSource.java

### ISSUE THREAD

**Issue by paulvonallwoerden** [WolverinDEV/TDFT#1]
It seems that TDFT is dependent on eclipse. I develop in vscode and get the following error when loading project H3.

```
java.lang.Exception: failed to initialize test source
	at dev.wolveringer.tdft.TestExecutor.initialize(TestExecutor.java:87)
	at dev.wolveringer.tdft.gui.MainForm.lambda$null$1(MainForm.java:86)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: failed to load project
	at dev.wolveringer.tdft.source.EclipseProjectSource.initialize(EclipseProjectSource.java:118)
	at dev.wolveringer.tdft.TestExecutor.initialize(TestExecutor.java:85)
	... 2 more
Caused by: java.lang.IllegalArgumentException: Failed to create directories for project file src/h3/PascalsTriangle.java
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at dev.wolveringer.tdft.source.EclipseProjectSource.extractProject(EclipseProjectSource.java:214)
	at dev.wolveringer.tdft.source.EclipseProjectSource.loadProject(EclipseProjectSource.java:222)
	at dev.wolveringer.tdft.source.EclipseProjectSource.initialize(EclipseProjectSource.java:116)
	... 3 more
```

Am I doing something wrong or is only eclipse supported?

If so, is support for other IDEs planned?

**Comment by WolverinDEV** [comment]
Hey,
you could only load exported projects with an eclipse like structure.
Like you're submitting as solution (the `.zip` file).

**Comment by Uelstudios** [comment]
The project has the following structure.
h03_xx_xx.zip

**Comment by WolverinDEV** [comment]
Uh my mistake failed to read the exception.
```
Failed to create directories for project file src/h3/PascalsTriangle.java
```
It comes from here: https://github.com/WolverinDEV/TDFT/blob/master/core/src/main/java/dev/wolveringer/tdft/source/EclipseProjectSource.java#L214
Seems a bit like you don't have permissions to create a folder within your TMP system directory.
Had you may tried to execute the app as administrator?

**Comment by paulvonallwoerden** [comment]
> Had you may tried to execute the app as administrator?
Executing the app as administrator instantly terminates the app. The bash window opens but instantly closes again.

**Comment by WolverinDEV** [comment]
Try to modify the script like this:
```
Change
java -jar %file% --plugin="./plugins/"
to
java java -Djava.io.tmpdir=./tmp/ -jar %file% --plugin="./plugins/"
```

**Comment by paulvonallwoerden** [comment]
Now files are created at the new tmp folder but the same errors as in https://github.com/WolverinDEV/TDFT/issues/1#issue-520495862 are shown. Even as admin.

TDFT-GUI
├───plugins
└───tmp
    ├───fop_compile_3722539605778013128
    │   ├───.settings
    │   ├───.vscode
    │   ├───bin
    │   │   └───h3
    │   ├───src
    │   └───__generated
    ├───fop_compile_6863955355666535154
    │   ├───.settings
    │   ├───.vscode
    │   ├───bin
    │   │   └───h3
    │   ├───src
    │   └───__generated
    └───fop_compile_8994698016919035301
        ├───.settings
        ├───.vscode
        ├───bin
        │   └───h3
        ├───src
        └───__generated


Edit: The folders TDFT-GUI\tmp\fop_compile_xxxx\\__generated are empty.

**Comment by WolverinDEV** [comment]
Could you may profile your .zip package?
Ofc you could cutout your code :)

**Comment by paulvonallwoerden** [comment]
Here are the contents of all files in my project

**/.project**
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>H03_vonallwoerden_paul</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
	</natures>
</projectDescription>
```

**/.classpath**
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/5"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

 **/.settings/org.eclipse.jdt.core.prefs**
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.codegen.unusedLocal=preserve
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.debug.lineNumber=generate
org.eclipse.jdt.core.compiler.debug.localVariable=generate
org.eclipse.jdt.core.compiler.debug.sourceFile=generate
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.source=1.8
```

**/.vscode/launch.json**
```
{
    "configurations": [
        {
            "type": "java",
            "name": "CodeLens (Launch) - PascalsTriangle",
            "request": "launch",
            "mainClass": "h3.PascalsTriangle",
            "projectName": "H03_NACHNAME_VORNAME"
        }
    ]
}
```

**/src/h3/PascalsTriangle.java**
```
package h3;

public class PascalsTriangle {
    public int faculty(int n) { }
    public int binomialCoefficient(int n, int k) { }
    public int[] triangleOfBinCoeff(int h) { }
    public int[] pascalsTriangle(int h) { }
}
```


**/src/main.java**
```
 import java.util.Arrays;

 import h3.PascalsTriangle;

 public class main {

    public static void main(String[] args) {
        PascalsTriangle pascalsTriangle = new PascalsTriangle();
        System.out.println(Arrays.toString(pascalsTriangle.triangleOfBinCoeff(6)));
        System.out.println(Arrays.toString(pascalsTriangle.pascalsTriangle(6)));
    }
 }
```

**/bin/main.class**
**/bin/h3/PascalsTriangle.class**

I hope that helps :-)

**Comment by WolverinDEV** [comment]
Ahh the `.vscode` folder is the issue.
I'll fix that
